### ISSUE TITLE
python - hacktoberfest: Add tests for list_all_notes method in user.py file

### ISSUE THREAD

**Issue by LeonardoFurtado** [LeonardoFurtado/OctoMemo#2]
EOM

**Comment by JMGama** [comment]
I can help you with this, can you tell me the idea or purpose  you have for that function just to save some time?

**Comment by ebarnsli** [comment]
Hate to steal this one from ya JGGamma but i think i submitted a PR for what @LeonardoFurtado  is actually asking for
